### ISSUE TITLE
안녕하세요 SRC오류 나서 이슈남깁니다.

### ISSUE THREAD

**Issue by k4584587** [nupamore/anisub#1]
애니메이션 자막 찾기까진 잘되는데 다운로드할때 링크를 못찾는것같내요..

[root@localhost node_modules]# anisub down "블렌드" "글라이더" 00110

애니메이션: 블렌드・S (ANISSIA)

자막제작자 찾는중..
글라이더
불량기념물
별명따위
미호리마
냥키치

에피소드: 00110화
http://blog.naver.com/parang567/221164868276

다운로드 링크 찾는중..
Blend+S+11.zip
Unhandled rejection TypeError: Cannot read property 'src' of undefined
    at anisub.parser.post.then.list (/usr/lib/node_modules/anisub/lib/main.js:124:34)
    at tryCatcher (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/anisub/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

[root@localhost node_modules]#

어떻게 하면 해결할수있을까요?

**Comment by nupamore** [comment]
앗 써주시는 분이 계셨네요. 반년넘게 건들지를 않았는데 ㅋㅋ
죄송하지만 구동환경과 anisub의 버전이 어떻게 되시나요? `anisub -V` 로 확인 가능합니다.
`v0.2.1`에서는 zip파일을 성공적으로 다운로드 받고.. 압축을 못푸네요 ㅠㅠㅠㅠㅠㅠ 확인해보겠습니다.

**Comment by k4584587** [comment]
CentOS 7 버전이랑 nodejs 에서 사용하고있습니다.
보니 재가 잘못한것도 있긴하내요 ㅎㅎ

fiter 부분에 ".zip" 입력해보니 다운되긴하내요 ㄷㄷ

**Comment by nupamore** [comment]
방금 퍼블리싱했습니다! 업데이트하고 다시 해보시겠어요?

**Comment by nupamore** [comment]
아 필터에 화수를 적으셨군요.. 몇 화인지 고르는게 아니라 파일이름 필터에요 ㅎㅎ

**Comment by k4584587** [comment]
잘되내요 ㅎㅎ 혹시 화수입력기능은 없나요?

**Comment by k4584587** [comment]
Error: ENOENT: no such file or directory, open 'package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.<anonymous> (/usr/lib/node_modules/anisub/bin/anisub.js:5:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
[root@localhost node_modules]#

어.. 갑자기 이런오류가 나오내요..ㄷㄷ

**Comment by nupamore** [comment]
뭐 때문인지 짐작은 가는데 왜 저한테선 그 오류가 안나는지 ㅠㅠ

**Comment by nupamore** [comment]
화수기능은 애니시아와 OHLI API에서 지원을 해주지 않습니다.
파싱으로 구현할까 했었는데 블로그 종류도 많고 예외처리할게 너무 많아서 힘들더라구요.

**Comment by k4584587** [comment]
아하 그렇군요.. 한번 재설치작업 시도 해보면서 해결해보겠습니다. 답변 감사합니다.

**Comment by nupamore** [comment]
package.json 문제 해결했습니다. 업데이트하시면 될거에요.
허접한 모듈 사용해주셔서 감사합니다. 다음에 내키시면 개발에 같이 참여해주세요 ㅎㅎ

**Comment by k4584587** [comment]
!! 방금 잘되는거 확인했습니다 ㅎㅎ
저는 자바 웹개발자라 노드는 힘들것같내요 ㅠㅠㅠ
